Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name: # サービス名
    Type: String
Resources:
  MyDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${App}-${Env}-${Name}-Dashboard' # ダッシュボード名(アプリ-環境-サービス名-Dashboard)
      DashboardBody: !Sub
        - |-
          {
            "widgets": [
              {
                "type": "metric",
                "x": 0,
                "y": 0,
                "width": 12,
                "height": 6,
                "properties": {
                  "metrics": [
                    [ "AWS/ECS", "CPUUtilization", "ClusterName", "${ECSClusterName}", "ServiceName", "${ECSServiceName}" ]
                  ],
                  "period": 300,
                  "stat": "Average",
                  "region": "${AWS::Region}",
                  "title": "CPU Utilization"
                }
              },
              {
                "type": "alarm",
                "x": 0,
                "y": 7,
                "width": 12,
                "height": 3,
                "properties": {
                  "title": "Service Alarms",
                  "alarms": [
                    "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${App}-${Env}-${Name}-HighCPUUtilization",
                    "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${App}-${Env}-${Name}-HighMemoryUtilization",
                    "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:${App}-${Env}-${Name}-High5xxErrorCount"
                  ]
                }
              }
            ]
          }
        # HighCPUUtilization,HighMemoryUtilization,High5xxErrorCountの内容は
        # テンプレ:アプリ名-環境名-サービス名.yamlに収録
        - ECSClusterName: !Sub "${App}-${Env}-Cluster"
          # ${App}-${Env}-ClusterId:Copilotが生成するクラスタID(ただしこのテンプレでは未使用)
          # CopilotがクラスタIDからECSクラスタ名を作成
          ECSServiceName: ${Name}
          # Copilotで作成されたECSサービス名
